In [16]:
import numpy as np

In [64]:
a = np.array([1, 2, 3])   # Create a rank 1 array
print(type(a))            # Prints "<class 'numpy.ndarray'>"      

<class 'numpy.ndarray'>


In [65]:
print(a.shape)            # Prints "(3,)"

(3,)


In [66]:
a.ndim

1

In [19]:
print(a[0], a[1], a[2])  # Prints "1 2 3"

1 2 3


In [20]:
a[0] = 5                  # Change an element of the array
print(a)   

[5 2 3]


In [21]:
a.dtype

dtype('int64')

In [22]:
a = np.array([1, 2, 3], dtype='float64') 

In [23]:
a

array([1., 2., 3.])

In [81]:
np.arange(4)

array([0, 1, 2, 3])

In [82]:
np.arange(10,15)

array([10, 11, 12, 13, 14])

In [83]:
np.arange(100,1000,10)

array([100, 110, 120, 130, 140, 150, 160, 170, 180, 190, 200, 210, 220,
       230, 240, 250, 260, 270, 280, 290, 300, 310, 320, 330, 340, 350,
       360, 370, 380, 390, 400, 410, 420, 430, 440, 450, 460, 470, 480,
       490, 500, 510, 520, 530, 540, 550, 560, 570, 580, 590, 600, 610,
       620, 630, 640, 650, 660, 670, 680, 690, 700, 710, 720, 730, 740,
       750, 760, 770, 780, 790, 800, 810, 820, 830, 840, 850, 860, 870,
       880, 890, 900, 910, 920, 930, 940, 950, 960, 970, 980, 990])

In [89]:
np.linspace(1,100,10)

array([  1.,  12.,  23.,  34.,  45.,  56.,  67.,  78.,  89., 100.])

In [90]:
b = np.array([[1,2,3],[4,5,6]])    # Create a rank 2 array
b

array([[1, 2, 3],
       [4, 5, 6]])

In [91]:
print(b.shape)                     # Prints "(2, 3)"

(2, 3)


In [92]:
b.ndim

2

In [93]:
b.itemsize #bytesize of each element

8

In [94]:
b.dtype

dtype('int64')

In [95]:
b.size

6

In [96]:
print(b[0, 0], b[0, 1], b[1, 0])   # Prints "1 2 4"

1 2 4


In [98]:
b.shape, b

((2, 3), array([[1, 2, 3],
        [4, 5, 6]]))

In [99]:
b.reshape(3,2)

array([[1, 2],
       [3, 4],
       [5, 6]])

In [101]:
b.ravel() #flatten

array([1, 2, 3, 4, 5, 6])

In [102]:
b

array([[1, 2, 3],
       [4, 5, 6]])

In [103]:
b.min()

1

In [104]:
b.max()

6

In [105]:
b.sum()

21

In [106]:
b.sum(axis=0) #colum sum

array([5, 7, 9])

In [107]:
b.sum(axis=1) #row sum

array([ 6, 15])

In [108]:
np.sqrt(b)

array([[1.        , 1.41421356, 1.73205081],
       [2.        , 2.23606798, 2.44948974]])

In [109]:
np.std(b)

1.707825127659933

In [27]:
a = np.zeros(2)   # Create an array of all zeros
print(a)            

[0. 0.]


In [28]:
a = np.zeros((3,3))   # Create an array of all zeros
print(a)

[[0. 0. 0.]
 [0. 0. 0.]
 [0. 0. 0.]]


In [29]:
a = np.ones((3,3))   # Create an array of all zeros
print(a)

[[1. 1. 1.]
 [1. 1. 1.]
 [1. 1. 1.]]


In [31]:
c = np.full((2,2), 9, dtype='float32')  # Create a constant array
print(c)

[[9. 9.]
 [9. 9.]]


In [32]:
d = np.eye(3)         # Create a 3x3 identity matrix
print(d)

[[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]]


In [36]:
e = np.random.random((2,3))  # Create an array filled with random values
print(e)                     # Might print "[[ 0.91940167  0.08143941]
                             #               [ 0.68744134  0.87236687]]"

[[0.66133624 0.44869918 0.89455598]
 [0.8133345  0.55979824 0.79928431]]


In [110]:
np1 = np.array([[1,2],[3,4]])
np2 = np.array([[5,6],[7,8]])

In [113]:
np1

array([[1, 2],
       [3, 4]])

In [114]:
np2

array([[5, 6],
       [7, 8]])

In [115]:
np1+np2

array([[ 6,  8],
       [10, 12]])

In [116]:
np1*np2

array([[ 5, 12],
       [21, 32]])

In [118]:
np1.dot(np2)

array([[19, 22],
       [43, 50]])


# Array Indexing


Slicing

In [121]:
a = np.array([6,7,8,9,10])

In [122]:
a[0:4]

array([6, 7, 8, 9])

In [123]:
a[-1]

10

In [125]:
a = np.array([[1,2,3,4], [5,6,7,8], [9,10,11,12]])
print(a)

[[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]]


In [126]:
a[0] #firstrow

array([1, 2, 3, 4])

In [127]:
a[-1] #lastrow

array([ 9, 10, 11, 12])

In [129]:
a[0,1:3] #firstrow & middle column

array([2, 3])

In [130]:
a[-1,2:4] #lastrow & middle column

array([11, 12])

In [132]:
a

array([[ 1,  2,  3,  4],
       [ 5,  6,  7,  8],
       [ 9, 10, 11, 12]])

In [134]:
for row in a:
  print(row)
  for cell in row:
    print(cell)

[1 2 3 4]
1
2
3
4
[5 6 7 8]
5
6
7
8
[ 9 10 11 12]
9
10
11
12


In [135]:
for cell in a.flat:
  print(cell)

1
2
3
4
5
6
7
8
9
10
11
12


In [46]:
a[1:3]

array([[ 5,  6,  7,  8],
       [ 9, 10, 11, 12]])

In [48]:
a[1:3,2:3]

array([[ 7],
       [11]])

In [49]:
a[-1]

array([ 9, 10, 11, 12])

Integer array indexing

In [53]:
a = np.array([[1,2], [3, 4], [5, 6]])
print(a)

[[1 2]
 [3 4]
 [5 6]]


In [51]:
print(a[[0, 1, 2], [0, 1, 0]])

[1 4 5]


In [54]:
print(np.array([a[0, 0], a[1, 1], a[2, 0]]))

[1 4 5]


In [55]:
print(a[[0, 0], [1, 1]])

[2 2]


In [57]:
print(np.array([a[0, 1], a[0, 1]]))  # Prints "[2 2]"

[2 2]


Stacking

In [140]:
arr1 = np.arange(6).reshape(2,3)
arr2 = np.arange(6,12).reshape(2,3)

In [141]:
arr1

array([[0, 1, 2],
       [3, 4, 5]])

In [142]:
arr2

array([[ 6,  7,  8],
       [ 9, 10, 11]])

In [143]:
np.vstack((arr1,arr2))

array([[ 0,  1,  2],
       [ 3,  4,  5],
       [ 6,  7,  8],
       [ 9, 10, 11]])

In [144]:
np.hstack((arr1,arr2))

array([[ 0,  1,  2,  6,  7,  8],
       [ 3,  4,  5,  9, 10, 11]])

In [145]:
x = np.arange(20).reshape(2,10)

In [146]:
x

array([[ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14, 15, 16, 17, 18, 19]])

In [150]:
result = np.hsplit(x,2)

In [151]:
result[0]

array([[ 0,  1,  2,  3,  4],
       [10, 11, 12, 13, 14]])

In [152]:
result[1]

array([[ 5,  6,  7,  8,  9],
       [15, 16, 17, 18, 19]])

In [153]:
result = np.vsplit(x,2)

In [154]:
result[0]

array([[0, 1, 2, 3, 4, 5, 6, 7, 8, 9]])

In [155]:
result[1]

array([[10, 11, 12, 13, 14, 15, 16, 17, 18, 19]])

In [160]:
m = np.arange(12).reshape(3,4)

In [161]:
m

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11]])

In [162]:
n = m > 6

In [163]:
n

array([[False, False, False, False],
       [False, False, False,  True],
       [ True,  True,  True,  True]])

In [164]:
m[n]

array([ 7,  8,  9, 10, 11])

In [165]:
m[n] = -1

In [166]:
m

array([[ 0,  1,  2,  3],
       [ 4,  5,  6, -1],
       [-1, -1, -1, -1]])

Array Iterating

In [167]:
a = np.arange(12).reshape(3,4)
a


array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11]])

In [168]:
for row in a:
  print(row)
  for cell in row:
    print(cell)

[0 1 2 3]
0
1
2
3
[4 5 6 7]
4
5
6
7
[ 8  9 10 11]
8
9
10
11


In [170]:
for cell in a.flatten(): # as well a.flat
  print(cell)

0
1
2
3
4
5
6
7
8
9
10
11


In [171]:
a

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11]])

In [172]:
for x in np.nditer(a, order='C'): #Go row by row : C Order
    print(x)

0
1
2
3
4
5
6
7
8
9
10
11


In [174]:
for x in np.nditer(a, order='F'): #Go column by column : Fortan Order
    print(x)

0
4
8
1
5
9
2
6
10
3
7
11


In [176]:
for x in np.nditer(a, flags=['external_loop'],order='F'): # print entire column instead of each element
    print(x)

[0 4 8]
[1 5 9]
[ 2  6 10]
[ 3  7 11]


In [177]:
for x in np.nditer(a, op_flags=['readwrite']):
    x[...] = x * x

In [179]:
a

array([[  0,   1,   4,   9],
       [ 16,  25,  36,  49],
       [ 64,  81, 100, 121]])

In [180]:
b = np.arange(3, 15, 4).reshape(3,1)
b

array([[ 3],
       [ 7],
       [11]])

In [181]:
for x, y in np.nditer([a,b]):
    print (x,y)

0 3
1 3
4 3
9 3
16 7
25 7
36 7
49 7
64 11
81 11
100 11
121 11
